<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.0.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NPOI" Version="2.7.2" />
    <PackageReference Include="System.IO.Abstractions" Version="21.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VFHCatalogMVC.Domain\VFHCatalogMVC.Domain.csproj" />
  </ItemGroup>

</Project>
