INSERT INTO PlantSections VALUES
('Tomato',1),
('Pepper',1),
('Potato',1),
('Eggplant',1),
('Other',1),
('Cucumber',2),
('Zucchini',2),
('Pumpkin',2),
('Patison',2),
('Other',2),
('Beans',3),
('Pea',3),
('Lentils',3),
('Broad bean',3),
('Other',3),
('Cabbage',4),
('Brussels sprouts',4),
('Broccoli',4),
('Cauliflower',4),
('Kohlrabi',4),
('Other',4),
('Lettuce',5),
('Spinach',5),
('Leaf parsley',5),
('Other',5),
('Onion',6),
('Garlic',6),
('Leek',6),
('Other',6),
('Carrot',7),
('Root parsley',7),
('Beetroot',7),
('Root celery', 7),
('Other', 7),
('Radish', 8),
('Rutabaga', 8),
('Turnip', 8),
('Other', 8),
('Cherries', 9),
('Peach', 9),
('Plum', 9),
('Apricot', 9),
('Other', 9),
('Strawberry', 10),
('Blackberries', 10),
('Blueberries', 10),
('Raspberries', 10),
('Currants', 10),
('Berries', 10),
('Other', 10),
('Apple', 11),
('Pear', 11),
('Quince', 11),
('Pomegranate ', 11),
('Other', 11),
('Lemon', 12),
('Tangerine', 12),
('Orange', 12),
('Grapefruit', 12),
('Other', 12),
('Banana', 13),
('Pineapple', 13),
('Lychee', 13),
('Other', 13);
