INSERT INTO PlantSections VALUES
('Pomidor',1),
('Paparyka',1),
('Ziemniak',1),
('Bak³a¿an',1),
('Inne',1),
('Ogórek',2),
('Cukinia',2),
('Dynia',2),
('Patison',2),
('Inne',2),
('Fasolka',3),
('Groszek',3),
('Soczewica',3),
('Bób',3),
('Inne',3),
('Kapusta',4),
('Brukselka',4),
('Broku³',4),
('Kalafior',4),
('Kalarepa',4),
('Inne',4),
('Sa³ata',5),
('Szpinak',5),
('Natka pietruszki',5),
('Inne',5),
('Cebula',6),
('Czosnek',6),
('Por',6),
('Inne',6),
('Marchewka',7),
('Pietruszka',7),
('Burak',7),
('Seler', 7),
('Inne', 7),
('Rzodkiewka', 8),
('Brukiew', 8),
('Rzepa', 8),
('Inne', 8),
('Wiœnia', 9),
('Brzoskiwnia', 9),
('Œliwka', 9),
('Morela', 9),
('Inne', 9),
('Truskawka', 10),
('Je¿yna', 10),
('Jagoda', 10),
('Malina', 10),
('Porzeczka', 10),
('Inne', 10),
('Jab³ko', 11),
('Gruszka', 11),
('Pigwa', 11),
('Granat ', 11),
('Inne', 11),
('Cytryna', 12),
('Mandarynka', 12),
('Pomarañcza', 12),
('Grejfrut', 12),
('Inne', 12),
('Banan', 13),
('Ananas', 13),
('Liczi', 13),
('Inne', 13);
