services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    volumes:
      - ./init/init-db.sql:/var/opt/mssql/scripts/init-db.sql
    networks:
      - sqlnet

  sqlclient:
    image: mcr.microsoft.com/mssql-tools
    container_name: sqlclient
    depends_on:
      - sqlserver
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    networks:
      - sqlnet

  aspnetapp:
    build:
      context: ../
      dockerfile: VFHCatalogMVC.Web/Dockerfile
    container_name: aspnetapp
    ports:
      - "8080:80"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=VFHCatalog;User=SA;Password=${SA_PASSWORD};
    networks:
      - sqlnet

networks:
  sqlnet: